spring.application.name=firstTaskForSpringBoot

#Server setting
server.port=8080

# Database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/FSDB
spring.datasource.username=postgres
spring.datasource.password=7625521195Olga
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false